spring:
  application:
    name: spring-test-service
  cloud:
    config:
      name: spring-test-service
      discovery:
        service-id: config-server
        enabled: true
      fail-fast: true
      retry:
        maxAttempts: 32
        multiplier: 1.5
        maxInterval: 10000
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTER_SERVER_URL:http://localhost:8761/eureka/,http://localhost:8762/eureka/}
  instance:
    prefer-ip-address: true
    hostname: spring-test-service
