server:
  port: 9091
spring:
  application:
    name: trace-1
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 1.0

#spring.zipkin.base-url=http://localhost:9411

#spring.sleuth.sampler.percentage=0.1

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTER_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: trace-1