server:
  port: 9092
spring:
  application:
    name: trace-2
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:spring-cloud-sleuth-zipkin
      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTER_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: trace-2