server:
  port: 8761

spring:
  profiles: peer1
  application:
    name: register-server
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/