server:
  port: 8762

spring:
  profiles: peer2
  application:
    name: register-server
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/