server:
  port: ${PORT:8089}
mybatis:
  mapper-locations: classpath*:com/hand/**/*Mapper.xml
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/spring-test-service?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=5
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PWD:123456}
      driver-class-name: com.mysql.jdbc.Driver